import type { Meta, StoryObj } from "@storybook/react";

const Welcome = (): React.ReactElement => {
  return (
    <div className="p-8 max-w-4xl mx-auto">
      <h1 className="text-4xl font-bold text-blue-900 mb-4">
        Welcome to Next.js Template Component Library
      </h1>

      <p className="text-lg text-gray-700 mb-6">
        This Storybook contains all reusable React components for the Next.js Template application.
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-blue-800 mb-3">Purpose</h2>
        <ul className="list-disc list-inside space-y-2 text-gray-700">
          <li>
            <strong>Component Development:</strong> Build and test components in isolation
          </li>
          <li>
            <strong>Documentation:</strong> Automatically generated documentation from code
          </li>
          <li>
            <strong>Agent Verification:</strong> Verify components generated by AI agents
          </li>
          <li>
            <strong>Design System:</strong> Maintain consistency across the application
          </li>
          <li>
            <strong>Quality Assurance:</strong> Test different states and edge cases
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-blue-800 mb-3">Component Organization</h2>
        <p className="text-gray-700 mb-3">
          Components are organized using Atomic Design principles:
        </p>

        <div className="space-y-4">
          <div className="p-4 bg-blue-50 rounded-lg">
            <h3 className="text-xl font-semibold text-blue-700 mb-2">Atoms</h3>
            <p className="text-gray-700">
              Basic building blocks that can&apos;t be broken down further: Buttons, Inputs, Labels,
              Icons
            </p>
          </div>

          <div className="p-4 bg-blue-100 rounded-lg">
            <h3 className="text-xl font-semibold text-blue-800 mb-2">Molecules</h3>
            <p className="text-gray-700">
              Simple combinations of atoms functioning together: Form fields, Cards, Navigation
              items
            </p>
          </div>

          <div className="p-4 bg-blue-50 rounded-lg">
            <h3 className="text-xl font-semibold text-blue-700 mb-2">Organisms</h3>
            <p className="text-gray-700">
              Complex components built from molecules and atoms: Forms, Navigation bars, Data tables
            </p>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-blue-800 mb-3">Getting Started</h2>
        <p className="text-gray-700 mb-3">
          Use the sidebar to navigate through available components. Each component has:
        </p>
        <ul className="list-disc list-inside space-y-2 text-gray-700">
          <li>Interactive controls to modify props</li>
          <li>Multiple stories showing different states</li>
          <li>TypeScript type definitions</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-blue-800 mb-3">Using Components</h2>
        <p className="text-gray-700 mb-3">
          All components can be imported from their respective folders:
        </p>
        <pre className="bg-blue-50 p-4 rounded-lg overflow-x-auto">
          <code className="text-sm text-gray-800">
            {`// Atoms
import { Button, Input, Label } from '@/components/atoms';

// Molecules
import { FormField, Card } from '@/components/molecules';

// Organisms
import { LoginForm } from '@/components/organisms';`}
          </code>
        </pre>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-blue-800 mb-3">Design Tokens</h2>
        <p className="text-gray-700 mb-3">
          This project uses design tokens accessible via Tailwind CSS:
        </p>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <h4 className="font-semibold text-gray-800 mb-2">Colors:</h4>
            <ul className="list-disc list-inside text-sm text-gray-700">
              <li>Blue shades (50-900)</li>
              <li>Gray shades (50-900)</li>
              <li>Semantic colors (red, green, etc.)</li>
            </ul>
          </div>
          <div>
            <h4 className="font-semibold text-gray-800 mb-2">Typography:</h4>
            <ul className="list-disc list-inside text-sm text-gray-700">
              <li>System font stack</li>
              <li>Responsive text sizes</li>
              <li>Font weights (400-900)</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-blue-800 mb-3">Best Practices</h2>
        <ol className="list-decimal list-inside space-y-2 text-gray-700">
          <li>Write TypeScript with proper types for all props</li>
          <li>Document props with JSDoc comments</li>
          <li>Create stories for all major states</li>
          <li>Use design tokens instead of hardcoded values</li>
          <li>Follow single responsibility principle</li>
        </ol>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-blue-800 mb-3">Resources</h2>
        <ul className="list-disc list-inside space-y-2 text-gray-700">
          <li>
            <a
              href="https://storybook.js.org/docs"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:underline"
            >
              Storybook Documentation
            </a>
          </li>
          <li>
            <a
              href="https://nextjs.org/docs"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:underline"
            >
              Next.js Documentation
            </a>
          </li>
          <li>
            <a
              href="https://tailwindcss.com/docs"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:underline"
            >
              Tailwind CSS
            </a>
          </li>
        </ul>
      </section>

      <div className="mt-8 p-6 bg-blue-50 rounded-lg border-l-4 border-blue-600">
        <p className="text-lg font-semibold text-blue-700">Happy coding! 🚀</p>
        <p className="text-gray-700 mt-2">Start exploring components in the sidebar →</p>
      </div>
    </div>
  );
};

const meta = {
  title: "Introduction/Welcome",
  component: Welcome,
  parameters: {
    layout: "fullscreen",
  },
} satisfies Meta<typeof Welcome>;

export default meta;
type Story = StoryObj<typeof meta>;

export const WelcomePage: Story = {};
